### ISSUE TITLE
Not display values

### ISSUE THREAD

**Issue by dvakerlis** [rukrlf/tier-price-date-range#1]
Hello and many thanks for your plugin! the problem is that after same when you go to see again the tier price table doesn't have any values in that fields (from date - to date). In the database I see the values...also in the front end is working fine. But doesn't show this values in the admin

**Comment by rukrlf** [comment]
Hi @dvakerlis 
Thanks for reporting this. I came across this issue and fixed it. may be I have not committed it. I will check and update.

**Comment by rukrlf** [comment]
Hi @dvakerlis, I checked the code and the fields are loaded from here
https://github.com/rukrlf/tier-price-date-range/blob/main/TierPriceDateRange/Model/ResourceModel/Product/Attribute/Backend/Tierprice.php

I checked it and it works as expected pls see the screen recording below;
[screen recording](https://drive.google.com/file/d/1wvFua8O5BtdFHhsqQeEyGmmnmmO9WI8w/view?usp=sharing)
Pls check if the values are passed correctly inside _loadPriceDataColumns fucntion in above class
Also check if the etc/di.xml file has the below "type" section defined correctly
`<type name="Magento\Catalog\Model\Product\Attribute\Backend\Tierprice">
        <arguments>
            <argument name="productAttributeTierprice" xsi:type="object">Rukshan\TierPriceDateRange\Model\ResourceModel\Product\Attribute\Backend\Tierprice</argument>
        </arguments>
    </type>`
